### PR TITLE
fix(pencil): update evm listeners for hardhat 2.11.0

### LINKED ISSUE #153: Hardhat 2.11.0 vm.on listener not present
**Describe the bug**

When uses `smock.fake` the following error is thrown when running test suites under hardhat 2.11.0

```
TypeError: vm.on is not a function
      at Function.fromEvent (node_modules/@defi-wonderland/smock/src/observable-vm.ts:42:8)
      at new ObservableVM (node_modules/@defi-wonderland/smock/src/observable-vm.ts:19:35)
      at new Sandbox (node_modules/@defi-wonderland/smock/src/sandbox.ts:36:15)
      at Function.create (node_modules/@defi-wonderland/smock/src/sandbox.ts:82:12)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at listOnTimeout (node:internal/timers:526:9)
      at processTimers (node:internal/timers:500:7)
      at init (node_modules/@defi-wonderland/smock/src/index.ts:27:13)
      at Object.fake (node_modules/@defi-wonderland/smock/src/index.ts:13:17)```

**Reproduction steps**

1. Use smock to fake a contract
2. Modify one response from a contract function 
3. Run test
4. See error

**Expected behavior**
vm.on or other methods of event listeners should allow users to use smock with the most recent versions of hardhat

**System Specs:**

- OS: Any
- Package Version (or commit hash): @defi-wonderland/smock@2.2.0

### PR DESCRIPTION
**Pull request by derekbar90**
**Description**
Fixed vm.on errors when running smock in a hardhat 2.11.0 environment

**Metadata**

- Fixes #153

### CODE REVIEW

**Comment by alcuadrado** [comment]
I believe the ethereumjs dependencies have to be upgraded to be on sync with these https://github.com/NomicFoundation/hardhat/blob/master/packages/hardhat-core/package.json#L102-L111

**Comment by 0xGorilla** [comment]
Any update on this?

**Comment by danielb1986** [comment]
It would be really nice if you could merge this pull request

**Comment by 0xOneTony** [comment]
@derekbar90 Latest commit (https://github.com/defi-wonderland/smock/commit/b71cfd118a2a9579517769c0c31abede7d83ca71) should fix the issues with hardhat 2.11.0!

**Comment by 0xGorilla** [comment]
This is fixed in version 2.3.0 of smock! Thanks @derekbar90 for being the first to point it out.

**Pull request closed without merging**
