### PR TITLE
change yarn lint

### PR DESCRIPTION
**Pull request by LadyChoupinette**
**Description**
A clear and concise description of the features you're adding in this pull request.
Change npm run to yarn as asked. Issue probably coming from IDE (vscode)
**Metadata**

- Fixes #[Link to Issue]

### CODE REVIEW

**Comment by wei3erHase** [comment]
doesn't seem to be achieving expectations, please read docs about husky!

**Comment by LadyChoupinette** [comment]
Thank you, but it does perfectly, as the expectation never mentioned that I should fix configuration problems on your side. 

You can try 'git config core.hooksPath ".husky" ', but do not expect lines of code to fix a problem of git/ide configuration.

**Comment by wei3erHase** [comment]
We do, actually.
Thanks for your interest in contributing!
I'm closing this PR now as there's no proposed roadmap to address the issue described on the task.
To be clear on the expectations:
- repo should `lint:fix` every time someone does `git commit`, this is totally unrelated to the IDE chosen, should also work with console.

**Comment by LadyChoupinette** [comment]
My interest is pointless if you do not try to understand what I'm saying. I already showed you that it worked. It is obviously linked to your configuration, and to be honest, the first Google search would have taught you that, whether it comes from vscode or your git configuration.

Thank you for the waste of time, the unprofessional attitude, and the clear lack of consideration (next time, redact correctly your bounty, thanks).

**Pull request closed without merging**
